### ISSUE TITLE
Merged dashboard PR has not led to dashboard updating

### ISSUE THREAD

**Issue by 0xneuratic** [anyone-protocol/ator-protocol#102]
This [merge](https://github.com/anyone-protocol/ator-relay-dashboard/commit/0b29af963fc857a179acd6d9f1b8c628a2b4d126) made by Malibu, bringing the dashboard version to v1.4.1, does not appear to have propagated to the gateways.

The GitHub [action](https://github.com/anyone-protocol/ator-relay-dashboard/actions/runs/11345209745/job/31551584368) appears to have run successfully. 

Not checked: the AR funds balance, not sure how to get deployer address

**Comment by kanshi** [comment]
I see 1.4.1 available.
I've checked the job yesterday and I've seen it succeed, so was suspecting this is just just a delay/glitch in propagating tx info into the naming system.
